version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
       - '3050:80'
  api:
    build:
    # Specify the folder where the build should start
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
    # Creating bookmarked + nornaml volumes
      - /app/node_modules
      - ./server:/app
    environment:
    # Since we have running services, we can just simply add their name!
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
      build:
      # Specify the folder where the build should start
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
      # Creating bookmarked + normal volumes
        - /app/node_modules
        - ./client:/app
  worker:
      build:
      # Specify the folder where the build should start
        context: ./worker
        dockerfile: Dockerfile.dev
      volumes:
      # Creating bookmarked + normal volumes
        - /app/node_modules
        - ./worker:/app
      environment:
      # Since we have running services, we can just simply add their name!
        - REDIS_HOST=redis
        - REDIS_PORT=6379